name: Export Zabbix Images
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and save images
        run: |
          docker pull zabbix/zabbix-server-mysql:6.4.14
          docker pull zabbix/zabbix-web-nginx-mysql:6.4.14
          docker save -o zabbix-6.4.tar zabbix/zabbix-server-mysql:6.4.14 zabbix/zabbix-web-nginx-mysql:6.4.14
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zabbix-images
          path: zabbix-6.4.tar
